routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::group(['middleware'=>'auth'],function(){
Route::get('/', 'Admin\DashboardController@index')->name('home');
});
Route::group(['prefix'=>'admin','middleware'=>'auth'],function(){
Route::get('/', 'Admin\DashboardController@index')->name('home');
Route::get('/users', 'Admin\UserController@index')->name('users');
Route::get('users/create', 'Admin\UserController@create')->name('user.create');

Route::post('users/store', 'Admin\UserController@store')->name('user.store');
Route::delete('users/delete/{id}', 'Admin\UserController@delete')->name('user.delete');

Route::get('users/edit/{id}','Admin\UserController@edit')->name('user.edit');
// Route::put('users/{$id}',function(){
// 	dd('sdfsd');
// })->name('user_update');

Route::put('users/update/{id}','Admin\UserController@update')->name('user_update');

Route::resource('company', 'Admin\CompanyController');

Route::post('employee/assign','Admin\CompanyController@assingEmployee')->name('employee.assign');

});

Route::get('logout', 'Admin\UserController@logOut')->name('adminlogout');
// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Company;
use App\Model\Employee;
use Image;
use Illuminate\Support\Facades\Storage;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companys = Company::paginate(10);
        return view('admin.company.index',compact('companys'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $this->validate($request, [
            'name'=>'required',
            'logo'=>'required|image|mimes:jpeg,png,jpg,gif,svg|dimensions:max_width=100,max_height=100',
             'website'=>'required',
             'email' => 'required|email|max:100|unique:companys',
          
        ]);


         $company = new Company();


        if ($request->hasFile('logo')) {
            $image      = $request->file('logo');
            $fileName   = time() . '.' . $image->getClientOriginalExtension();
            

            $img = Image::make($image->getRealPath());
            $img->resize(100, 100, function ($constraint) {
                $constraint->aspectRatio();                 
            });

            $img->stream(); 

            Storage::disk('local')->put('public/images'.'/'.$fileName, $img, 'public');
        
            }

// dd($fileName);
        $company->logo = $fileName;
        $company->name = $request->name;
        $company->website = $request->website;
        // $company->logo = $request->logo;
        $company->email = $request->email;


        $company->save();

       return redirect()->route('company.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::findOrFail($id);
        // dd($company);
        return view('admin.company.edit',compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $this->validate($request, [
            'name'=>'required',
            'logo'=>'sometimes|image|mimes:jpeg,png,jpg,gif,svg|dimensions:max_width=100,max_height=100',
             'website'=>'required',
             'email' => 'required|email|max:100|unique:companys,email,'.$id,
            
          
        ]);


         $company = Company::findOrFail($id);

        if ($request->hasFile('logo')) {
            $image      = $request->file('logo');
            $fileName   = time() . '.' . $image->getClientOriginalExtension();
            

            $img = Image::make($image->getRealPath());
            $img->resize(100, 100, function ($constraint) {
                $constraint->aspectRatio();                 
            });

            $img->stream(); 

            Storage::disk('local')->put('public/images'.'/'.$fileName, $img, 'public');
            $company->logo = $fileName;
            
             if(\Storage::exists('public/images/'.$company->logo)){
            // dd('file exists');

                \Storage::delete('public/images/'.$company->logo);
                //Storage::delete($path . $filename_old);

              }

            }

                
                $company->name = $request->name;
                $company->website = $request->website;
                // $company->logo = $request->logo;
                $company->email = $request->email;


                $company->save();

               return redirect()->route('company.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
            $company = Company::findorFail($id);
            $company->delete();
             if(\Storage::exists('public/images/'.$company->logo)){
                // dd('file exists');

                    \Storage::delete('public/images/'.$company->logo);
                //Storage::delete($path . $filename_old);

              }
        return redirect()->route('company.index');
    }

    public function assingEmployee(Request $request){
        // dd($request->all());

        if ($request->has('comp_id')) {
            // dd('success');
          $emp_id = $request->emp_id;
        $comp_id = $request->comp_id;

        $employee = Employee::findOrFail($emp_id);
        $employee->company_id = $comp_id;
        $employee->save();




            $response['status'] = "success";
            $response['company'] = $comp_id;
            $response['employee'] = $employee;
            return response()->json($response);
        }
        

    }
}

resources/views/admin/company/create.blade.php
@extends('layouts.master')
@section('page_title')
| Create Company
@endsection
@section('contents')
<div class="mdc-layout-grid">
            <div class="mdc-layout-grid__inner">
             
              <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12 mdc-layout-grid__cell--span-8-tablet">

                <div class="mdc-card">
                  <div class="template-demo">
                    @if ($errors->any())
    <div class="alert alert-warning">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
                  <h6 class="card-title card-padding pb-0">Create Company</h6>

              <form action="{{ route('company.store') }}" method="post" enctype="multipart/form-data">
                @method('POST')
                @csrf
                    <div class="mdc-layout-grid">
                      <div class="mdc-layout-grid__inner">
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
                          <div class="mdc-text-field w-100">
                            <input type="text" name="name" class="mdc-text-field__input" id="text-field-hero-input">
                            <div class="mdc-line-ripple"></div>
                            <label for="text-field-hero-input" class="mdc-floating-label">Name <span style="color: #ff0000;padding-left: 2px;">*</span></label>
                          </div>
                        </div>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">

                          <div class="mdc-text-field w-100">
                            
                           
                      <input type="file" name="logo" class="form-control" id="banner" placeholder="Logo" value="{{ old('banner') }}">
                      <label for="exampleInputEmail3">Logo <span style="color: #ff0000;padding-left: 0px;">*</span></label>
                            
                          
                          </div>
                        </div>

                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
                          <div class="mdc-text-field w-100">
                            <input type="text" name="website" class="mdc-text-field__input" id="text-field-hero-input">
                            <div class="mdc-line-ripple"></div>
                            <label for="text-field-hero-input" class="mdc-floating-label">Website</label>
                          </div>
                        </div>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                          <div class="mdc-text-field w-100">
                            <input type="email" name="email" class="mdc-text-field__input" id="text-field-hero-input">
                            <div class="mdc-line-ripple"></div>
                            <label for="text-field-hero-input" class="mdc-floating-label">Email <span style="color: #ff0000;padding-left: 2px;">*</span></label>
                          </div>
                        </div>
                      
                       
                        
                       
                       
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                          <button type="submit" class="mdc-button mdc-button--raised">
                           Create Company
                        </button>
                        </div>
                      </div>
                    </div>
                  </form>

                </div>
                </div>
              </div>
           
            </div>
          </div>
@endsection

resources/views/admin/company/edit.blade.php
@extends('layouts.master')
@section('page_title')
| Edit Company
@endsection
@section('contents')
<div class="mdc-layout-grid">
            <div class="mdc-layout-grid__inner">
             
              <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12 mdc-layout-grid__cell--span-8-tablet">

                <div class="mdc-card">
                  <div class="template-demo">
                    @if ($errors->any())
    <div class="alert alert-warning">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
                  <h6 class="card-title card-padding pb-0">Update Company</h6>

              <form action="{{ route('company.update',$company->id) }}" method="post" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                    <div class="mdc-layout-grid">
                      <div class="mdc-layout-grid__inner">
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
                          <div class="mdc-text-field w-100">
                            <input type="text" name="name" value="{{ $company->name }}" class="mdc-text-field__input" id="text-field-hero-input">
                            <div class="mdc-line-ripple"></div>
                            <label for="text-field-hero-input" class="mdc-floating-label">Name <span style="color: #ff0000;padding-left: 2px;">*</span></label>
                          </div>
                        </div>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">

                          <div class="mdc-text-field w-100">
                            <img src="{{ asset('storage/images/'.$company->logo) }}" width="50px"
                                                height="50px"/>
                           
                      <input type="file" name="logo" class="form-control" id="banner" value="{{ $company->logo }}" placeholder="Logo" value="{{ old('banner') }}">
                      <label for="exampleInputEmail3">Logo <span style="color: #ff0000;padding-left: 0px;">*</span></label>
                            
                          
                          </div>
                        </div>

                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
                          <div class="mdc-text-field w-100">
                            <input type="text" name="website" value="{{ $company->website }}" class="mdc-text-field__input" id="text-field-hero-input">
                            <div class="mdc-line-ripple"></div>
                            <label for="text-field-hero-input" class="mdc-floating-label">Website</label>
                          </div>
                        </div>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                          <div class="mdc-text-field w-100">
                            <input type="email" name="email" value="{{ $company->email }}" class="mdc-text-field__input" id="text-field-hero-input">
                            <div class="mdc-line-ripple"></div>
                            <label for="text-field-hero-input" class="mdc-floating-label">Email <span style="color: #ff0000;padding-left: 2px;">*</span></label>
                          </div>
                        </div>
                      
                       
                        
                       
                       
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                          <button type="submit" class="mdc-button mdc-button--raised">
                           Update Company
                        </button>
                        </div>
                      </div>
                    </div>
                  </form>

                </div>
                </div>
              </div>
           
            </div>
          </div>
@endsection

resources/views/admin/company/index.blade.php
@extends('layouts.master')
@section('page_title')
| Companies
@endsection
@section('styles')
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 

@endsection
@section('contents')
<div class="mdc-layout-grid">
            <div class="mdc-layout-grid__inner">
             
              <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12 mdc-layout-grid__cell--span-8-tablet">

                <div class="mdc-card">
                  <div class="template-demo">
                   
                  <a href="{{ route('company.create') }}"><button type="button" class="mdc-button mdc-button--raised">
                      Create Company
                    </button></a>
                  <h6 class="card-title card-padding pb-0">Company Table</h6>

                  <div class="table-responsive">

                    <table class="table table-hoverable">
                      <thead>
                        <tr>
                          <th class="text-left">Name</th>
                          <th class="text-left">Last Name</th>
                          <th class="text-left">Email</th>
                          <th class="text-left">Status</th>
                          <th class="text-left">Action</th>
                        
                          
                         
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($companys as $company)
                        <tr >
                          <td class="text-left">{{ $company->name }}</td>
                          <td class="text-left">{{ $company->logo }}
                            <img src="{{ asset('storage/images/'.$company->logo) }}" width="50px"
                                                height="50px"/></td>
                          <td class="text-left">{{ $company->email }}</td>
                          <td class="text-left">{{ $company->website }}</td>
                         <td class="text-left">
                             <a href="{{ route('company.edit',$company->id) }}" class="mdc-button mdc-button--raised">
                                    edit
                                </a>
                            
                                <form action="{{ route('company.destroy',$company->id) }}" class="delform"
                                      style="display: inline;" method="post"
                                      onsubmit="return confirm('Are you sure')">
                                    @csrf
                                    @method('DELETE')
                                    <button class="mdc-button mdc-button--raised icon-button filled-button--secondary">
                        <i class="material-icons mdc-button__icon">delete</i>
                      </button>
                                </form>
                         </td>
                        </tr>
                        @endforeach
                       
                      </tbody>
                      {{ $companys->links() }}
                    </table>
                  </div>


                </div>
                </div>
              </div>
           
            </div>
          </div>
@endsection